import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jason Yecyec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID as string} />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <iframe
          src="https://smartchat-ai.smartcontents.co.jp/widget?chatbot_id=019a354c-e98e-7272-a94e-3801b8324509"
          style={{
            position: "fixed",
            bottom: 20,
            right: 20,
            width: 400,
            height: 600,
            border: "none",
            borderRadius: 12,
            backgroundColor: "transparent",
            zIndex: 9999,
          }}
          allow="clipboard-write"
          title="BizChat Support Widget"
        ></iframe>
      </body>
    </html>
  );
}
